services:
  graveto:
    image: ghcr.io/ferreiraman/graveto:latest
    container_name: graveto_backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - GRAVETO_POSTGRES_HOST=postgres
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}     
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    container_name: graveto_db
    ports:
      - "5432:5432"    
    volumes:
      - ./graveto-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}