services:
  graveto:
    image: ghcr.io/ferreiraman/graveto:latest
    container_name: graveto_backend_staging
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      - GRAVETO_POSTGRES_HOST=postgres
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_APP_USER=${GRAVETO_APP_USER}
      - POSTGRES_APP_PASSWORD=${GRAVETO_APP_PASSWORD}
      - POSTGRES_MIGRATOR_USER=${GRAVETO_MIGRATOR_USER}
      - POSTGRES_MIGRATOR_PASSWORD=${GRAVETO_MIGRATOR_PASSWORD}   
      - YFINANCE_API_KEY=${YFINANCE_API_KEY}
    depends_on:
      - postgres

  postgres:
    image: ghcr.io/ferreiraman/graveto-postgres:latest
    container_name: graveto_db_staging
    ports:
      - "5433:5432"    
    volumes:
      - ./graveto-db-data-staging:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_APP_USER=${GRAVETO_APP_USER}
      - POSTGRES_APP_PASSWORD=${GRAVETO_APP_PASSWORD}
      - POSTGRES_MIGRATOR_USER=${GRAVETO_MIGRATOR_USER}
      - POSTGRES_MIGRATOR_PASSWORD=${GRAVETO_MIGRATOR_PASSWORD}   